name: Release

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build -c Release src/ApiAlerts.Common/ApiAlerts.Common.csproj
      - name: Test
        run: dotnet test src/ApiAlerts.Common/ApiAlerts.Common.csproj --no-build --verbosity normal
      - name: Pack NuGets
        run: dotnet pack -c Release src/ApiAlerts.Common/ApiAlerts.Common.csproj --no-build --output .
      - name: Send Build Alert
        working-directory: ./sample
        run: run dotnet run --project Script.GitHub/Program.cs -- release
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
        
