name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0'
      - name: Build
        run: dotnet build -c Release src/APIAlerts/APIAlerts.csproj
      - name: Test
        run: dotnet test --verbosity normal
      - name: Pack
        run: dotnet pack src/APIAlerts/APIAlerts.csproj -c Release --no-build --output ./nupkg
      - name: Notify
        run: dotnet run --project sample/ApiAlerts.Sample.csproj -- --release
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
