name: Publish

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build -c Release src/APIAlerts/APIAlerts.csproj
      - name: Test
        run: dotnet test src/APIAlerts/APIAlerts.csproj --no-build --verbosity normal
      - name: Pack NuGets
        run: dotnet pack -c Release src/APIAlerts/APIAlerts.csproj --no-build --output .
      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
      - name: Send Build Alert
        run: run dotnet run --project Script.GitHub/Program.cs -- publish
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
